import type config from "./config.json";

/**
 * The contract between the React app and the standalone voxel engine.
 *
 * The engine (`engine/index.js`, bundled to `/prismarine/game.js`) is plain JS
 * outside the Next build, so this file is the only place its shape is written
 * down. `world.meta.json` is generated by `scripts/mc/gen-content.mjs` from the
 * anchors `build-world.mjs` emits — change one, change the other.
 */

export type McConfig = typeof config;

export interface Vec3Like {
  x: number;
  y: number;
  z: number;
}

/** One classroom slot in the generated campus. */
export interface RoomAnchor {
  index: number;
  wing: "north" | "east" | "west" | "south";
  /** Room number as painted on the plan: N1, E2, S3… */
  name: string;
  /** Interior, inclusive block coordinates. */
  bounds: { min: Vec3Like; max: Vec3Like };
  centre: Vec3Like;
  door: Vec3Like & {
    facing: "north" | "south" | "east" | "west";
    /** Where to stand in the corridor, looking in — the `?event=` spawn. */
    outside: Vec3Like;
  };
  sign: Vec3Like & { facing: "north" | "south" | "east" | "west" };
  label: Vec3Like;
  board: {
    cx: number;
    cy: number;
    cz: number;
    axis: "x" | "z";
    dir: 1 | -1;
    w: number;
    h: number;
  };
}

export interface WorldMeta {
  version: string;
  size: { w: number; h: number; l: number };
  ground: number;
  floor: number;
  spawn: Vec3Like & { yaw: number };
  rooms: RoomAnchor[];
  pois: Record<string, Vec3Like & Record<string, unknown>>;
  renderDistance: number;
}

/**
 * What the engine draws on one classroom. Serialisable on purpose: it crosses
 * from React into a script that shares no modules with the app.
 */
export interface RoomBinding {
  index: number;
  /** The event living here, or null for a spare / "coming soon" room. */
  slug: string | null;
  label: string;
  /** Short lines for the wall sign beside the door. */
  signLines: string[];
  /** Fact lines for the board inside (kind, date, time, venue, prizes…). */
  boardLines: string[];
  /** Whether standing inside offers "Press E" and opens a hub. */
  interactive: boolean;
}

export interface EngineHandle {
  dispose: () => void;
  /** A React modal is open: release the mouse and freeze the player. */
  setUiOpen: (open: boolean) => void;
  teleportToRoom: (index: number) => boolean;
  setBindings: (bindings: RoomBinding[]) => void;
  toast: (text: string) => void;
}

export interface EngineStartOptions {
  container: HTMLElement;
  config: McConfig;
  playerName: string;
  meta: WorldMeta;
  bindings: RoomBinding[];
  spawnRoom?: number;
  onOpenEvent: (slug: string) => void;
  onStatus?: (message: string) => void;
  onProgress?: (t: number) => void;
}

declare global {
  interface Window {
    McGateways?: {
      version: string;
      start: (opts: EngineStartOptions) => Promise<EngineHandle>;
    };
    /** Absolute base URL of a CDN mirroring `public/prismarine`, if any. */
    __MC_CDN_BASE?: string;
    /** PartyKit host for multiplayer — unset in this build (see engine/net). */
    __MC_MP_HOST?: string;
    __mcDebug?: Record<string, unknown>;
  }
}
