/**
 * Turns the coordinates emitted by build-world.mjs into the small
 * public/prismarine/world.meta.json the engine (and the React side) read
 * before downloading anything heavy.
 *
 * Event names are NOT bound here: the classrooms are numbered slots, and the
 * runtime binds the live event list onto them (src/frontend/lib/minecraft/
 * bind-rooms.ts). That is what lets the Google Sheet change without a rebuild.
 *
 * Run AFTER `npm run mc:world`.  ->  npm run mc:content
 */
import fs from 'node:fs'
import path from 'node:path'
import { ANCHORS, OUT, config } from './paths.mjs'

if (!fs.existsSync(ANCHORS)) {
  console.error('Missing .cache/mc/world-anchors.json — run `npm run mc:world` first.')
  process.exit(1)
}
const anchors = JSON.parse(fs.readFileSync(ANCHORS, 'utf8'))

fs.mkdirSync(OUT, { recursive: true })
fs.writeFileSync(path.join(OUT, 'world.meta.json'), JSON.stringify({
  _README: 'GENERATED by scripts/mc/gen-content.mjs from scripts/mc/build-world.mjs — DO NOT EDIT BY HAND.',
  version: anchors.version,
  size: anchors.size,
  ground: anchors.ground,
  floor: anchors.floor,
  spawn: anchors.spawn,
  rooms: anchors.rooms,
  pois: anchors.pois,
  renderDistance: config.world?.renderDistance ?? 4
}, null, 1) + '\n')

console.log(`world.meta.json  ${anchors.rooms.length} rooms, spawn ${JSON.stringify(anchors.spawn)}`)
